#!/usr/bin/env bash

function _wait() {
    sleep 1
}

function _log() {
    echo "--------------------------------------------------------------------"
    echo ""
    echo $1
    echo ""
    echo "--------------------------------------------------------------------"
    echo ""

    # _wait
}

function main() {
    _log "Setting up the system..."

    _log "Setting up vim as EDITOR"
    export EDITOR=vim

    _log "Time..."
    ln -sf /usr/share/zoneinfo/America/Bogota /etc/localtime
    hwclock --systohc

    _log "Localization..."
    _log "uncomment en_US.UTF-8 UTF 8"
    vim /etc/locale.gen

    _log "Making locale.conf..."
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    cat /etc/locale.conf

    _log "Hostname..."
    echo "nikola" > /etc/hostname
    cat /etc/hostname

    _log "Root password..."
    passwd

    _log "Add nikola user..."
    useradd -m -G wheel -s /bin/bash nikola

    _log "nikola password..."
    passwd nikola

    _log "Add sudo permitions to the user..."
    _log "uncomment %wheel ALL=(ALL:ALL) ALL"
    EDITOR=vim visudo

    _log "Installing minimal required dependencies..."
    pacman -S sudo networkmanager grub

    _log "Network configuration..."
    systemctl enable NetworkManager

    _log "Bootloader..."
    grub-install --target=x86_64-efi --efi-directory=/boot

    _log "Config GRUB"
    grub-mkconfig -o /boot/grub/grub.cfg

    _log "Reboot"
    sleep 1
    exit
}

main
