#!/usr/bin/env bash

function _setup_font() {
    setfont ter-v22b
}

function _wait() {
    sleep 2
}

function _log() {
    clear
    echo ""
    echo "--------------------------------------------------------------------"
    echo $1
    echo ""
    echo "--------------------------------------------------------------------"
    echo ""
}

function _show_disk_partitions() {
    _log "Showing /dev/sda state..."
    lsblk
    _wait
}

function main() {
    _log "Setting up vim as $EDITOR"
    export EDITOR=vim

    _log "Setting up console font..."
    _setup_font

    _log "Updatting keyring..."
    pacman -Sy archlinux-keyring --noconfirm

    _show_disk_partitions

    _log "Format the partitions with cfdisk"
    cfdisk /dev/sda

    _show_disk_partitions

    _log "Formatting partitions..."

    _log "Formatting boot partition (sda1)"
    mkfs.fat -F 32 /dev/sda1

    _log "Formatting SWAP partition (sda1)"
    mkswap /dev/sda2

    _log "Formatting root partition (sda3)"
    mkfs.ext4 /dev/sda3

    _show_disk_partitions

    _log "Mountting paratitions..."

    _log "Mounting boot partition (sda1)"
    mount --mkdir /dev/sda1 /mnt/boot

    _log "Mounting SWAP partition (sda2)"
    swapon /dev/sda2

    _log "Mounting root partition (sda3)"
    mount /dev/sda3 /mnt

    _show_disk_partitions

    _log "Edit pacman.conf to improve perf..."
    _log "Color, ILoveCandy, ParallelDownloads = 10"

    _wait

    sudoedit /etc/pacman.conf

    _log "Installing essential packages..."
    pacstrap -K /mnt base linux linux-firmware

    _log "Setting up the system..."

    _log "Fstab..."
    genfstab -U /mnt >> /mnt/etc/fstab

    _log "Chroot..."
    arch-chroot /mnt

    _log "Time..."
    ln -sf /usr/share/zoneinfo/America/Bogota /etc/localtime
    hwclock --systohc

    _log "Localization..."
    _log "uncomment en_US.UTF-8 UTF 8"
    vim /etc/locale.gen

    _log "Making locale.conf..."
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    cat /etc/locale.conf

    _log "Hostname..."
    echo "nikola" > /etc/hostname
    cat /etc/hostname

    _log "Root password..."
    passwd

    _log "Add nikola user..."
    useradd -m -G wheel -s /bin/bash nikola

    _log "nikola password..."
    passwd nikola

    _log "Add sudo permitions to the user..."
    _log "uncomment %wheel ALL=(ALL:ALL) ALL"
    EDITOR=vim visudo

    _log "Network configuration..."

    echo "continue developing"
    # #+begin_src bash
    # systemctl enable NetworkManager
    # #+end_src
    # ** Bootloader
    # #+begin_src bash
    # grub-install --target=x86_64-efi --efi-directory=/mnt/boot
    # os-prober
    # grub-mkconfig -o /boot/grub/grub.cfg
    # EDITOR=vim sudoedit /etc/default/grub
    # GRUB_TIMEOUT=3600
    # # uncomment GRUB_DISABLE_OS_PROBER=false
    # grub-mkconfig -o /boot/grub/grub.cfg
    # #+end_src
    # ** Reboot
    # #+begin_src bash
    # exit
    # umount -R /mnt
    # reboot
    # #+end_src
    #
    # * Post install
    # ** Update =pacman.conf=
    # #+begin_src bash
}

main
