#!/usr/bin/env bash

function _setup_font() {
    setfont ter-v22b
}

function _wait() {
    sleep 2
}

function _log() {
    echo "--------------------------------------------------------------------"
    echo ""
    echo $1
    echo ""
    echo "--------------------------------------------------------------------"
    echo ""

    _wait
}

function _show_disk_partitions() {
    _log "Showing /dev/sda state..."
    lsblk
    _wait
}

function main() {
    _log "Setting up vim as $EDITOR"
    export EDITOR=vim

    _log "Setting up console font..."
    _setup_font

    _log "Updatting keyring..."
    pacman -Sy archlinux-keyring --noconfirm

    _show_disk_partitions

    _log "Format the partitions with cfdisk"
    cfdisk /dev/sda

    _show_disk_partitions

    _log "Formatting partitions..."

    _log "Formatting boot partition (sda1)"
    mkfs.fat -F 32 /dev/sda1

    _log "Formatting SWAP partition (sda1)"
    mkswap /dev/sda2

    _log "Formatting root partition (sda3)"
    mkfs.ext4 /dev/sda3

    _show_disk_partitions

    _log "Mountting paratitions..."

    _log "Mounting boot partition (sda1)"
    mount --mkdir /dev/sda1 /mnt/boot

    _log "Mounting SWAP partition (sda2)"
    swapon /dev/sda2

    _log "Mounting root partition (sda3)"
    mount /dev/sda3 /mnt

    _show_disk_partitions

    _log "Edit pacman.conf to improve perf..."
    _log "Color, ILoveCandy, ParallelDownloads = 10"

    _wait

    sudoedit /etc/pacman.conf

    _log "Installing essential packages..."
    pacstrap -K /mnt base linux linux-firmware git

    _log "Setting up the system..."

    _log "Fstab..."
    genfstab -U /mnt >> /mnt/etc/fstab

    _log "Chroot..."
    arch-chroot /mnt
}

main
